// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANT_LING_MODELS } from "./providers/ant-ling.models.ts";
import { AZURE_OPENAI_RESPONSES_MODELS } from "./providers/azure-openai-responses.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { MISTRAL_MODELS } from "./providers/mistral.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { XAI_MODELS } from "./providers/xai.models.ts";

export const MODELS = {
	"ant-ling": ANT_LING_MODELS,
	"azure-openai-responses": AZURE_OPENAI_RESPONSES_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"mistral": MISTRAL_MODELS,
	"openai": OPENAI_MODELS,
	"openai-codex": OPENAI_CODEX_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"xai": XAI_MODELS,
} as const;
