export type MarketplaceKind = "skills" | "mcp" | "repositories";

export interface MarketplacePackage {
	id: string;
	kind: MarketplaceKind;
	name: string;
	packageName: string;
	version: string;
	source: string;
	publisher: string;
	description: string;
	tags: string[];
}

export const MCP_ADAPTER_MARKETPLACE_PACKAGE: MarketplacePackage = {
	id: "pi-mcp-adapter",
	kind: "mcp",
	name: "Pi MCP Adapter",
	packageName: "pi-mcp-adapter",
	version: "2.11.0",
	source: "npm:pi-mcp-adapter@2.11.0",
	publisher: "Nico Bailon",
	description: "Connect Pi to standard MCP server configurations with lazy tool discovery and compact context usage.",
	tags: ["Adapter", "Lazy tools", "OAuth"],
};

export const MARKETPLACE_PACKAGES: MarketplacePackage[] = [
	{
		id: "bigpowers",
		kind: "skills",
		name: "BigPowers",
		packageName: "bigpowers",
		version: "2.77.2",
		source: "npm:bigpowers@2.77.2",
		publisher: "Daniel V.",
		description: "73 engineering skills covering specifications, testing, debugging, review, and delivery.",
		tags: ["TDD", "Planning", "Review"],
	},
	{
		id: "superpowers-zh",
		kind: "skills",
		name: "Superpowers ZH",
		packageName: "superpowers-zh",
		version: "1.7.1",
		source: "npm:superpowers-zh@1.7.1",
		publisher: "jnMetaCode",
		description: "Chinese-localized Superpowers skills with TDD, debugging, and code-review workflows.",
		tags: ["Chinese", "Debugging", "Review"],
	},
	{
		id: "mitsupi",
		kind: "skills",
		name: "Mitsupi",
		packageName: "mitsupi",
		version: "1.6.0",
		source: "npm:mitsupi@1.6.0",
		publisher: "Armin Ronacher",
		description: "A curated Pi collection of skills, commands, extensions, and themes for daily development.",
		tags: ["Workflow", "Commands", "Themes"],
	},
	{
		id: "pi-web-access",
		kind: "skills",
		name: "Pi Web Access",
		packageName: "pi-web-access",
		version: "0.13.0",
		source: "npm:pi-web-access@0.13.0",
		publisher: "Nico Bailon",
		description: "Web search, fetching, GitHub cloning, PDF extraction, and video analysis skills for Pi.",
		tags: ["Web", "GitHub", "PDF"],
	},
	{
		id: "pi-experiences",
		kind: "skills",
		name: "Pi Experiences",
		packageName: "pi-experiences",
		version: "0.1.49",
		source: "npm:pi-experiences@0.1.49",
		publisher: "misunders2d",
		description: "Local-first, human-reviewed habits that add behavioral learning alongside skills and memory.",
		tags: ["Habits", "Memory", "Local-first"],
	},
	{
		id: "ponytail",
		kind: "skills",
		name: "Ponytail",
		packageName: "@dietrichgebert/ponytail",
		version: "4.8.4",
		source: "npm:@dietrichgebert/ponytail@4.8.4",
		publisher: "Dietrich Gebert",
		description: "Senior-development skills focused on reducing unnecessary code and keeping changes maintainable.",
		tags: ["Architecture", "Simplicity", "Review"],
	},
	MCP_ADAPTER_MARKETPLACE_PACKAGE,
	{
		id: "context-mode",
		kind: "mcp",
		name: "Context Mode",
		packageName: "context-mode",
		version: "1.0.169",
		source: "npm:context-mode@1.0.169",
		publisher: "mksglu",
		description: "Context-efficient MCP workflows with sandboxed execution, indexed knowledge, and focused search.",
		tags: ["Context", "Sandbox", "Search"],
	},
	{
		id: "pi-lean-ctx",
		kind: "mcp",
		name: "Lean Context",
		packageName: "pi-lean-ctx",
		version: "3.9.12",
		source: "npm:pi-lean-ctx@3.9.12",
		publisher: "yvgude",
		description: "Routes file and shell operations through compact output with a persistent MCP-backed cache.",
		tags: ["Compression", "Cache", "Tools"],
	},
	{
		id: "pi-fabric",
		kind: "mcp",
		name: "Pi Fabric",
		packageName: "pi-fabric",
		version: "0.22.4",
		source: "npm:pi-fabric@0.22.4",
		publisher: "monotykamary",
		description: "Programmable tool and agent runtime with MCP, subagents, actors, and workflow orchestration.",
		tags: ["Runtime", "Agents", "Workflows"],
	},
	{
		id: "pi-shazam",
		kind: "mcp",
		name: "Pi Shazam",
		packageName: "pi-shazam",
		version: "0.30.0",
		source: "npm:pi-shazam@0.30.0",
		publisher: "gjczone",
		description: "Structural codebase analysis tools for Pi with Tree-sitter, LSP, PageRank, and MCP support.",
		tags: ["Codebase", "LSP", "Analysis"],
	},
	{
		id: "gentle-engram",
		kind: "mcp",
		name: "Gentle Engram",
		packageName: "gentle-engram",
		version: "0.1.10",
		source: "npm:gentle-engram@0.1.10",
		publisher: "Gentleman Programming",
		description: "Persistent project memory shared across Pi sessions, compactions, and MCP agents.",
		tags: ["Memory", "Sessions", "Cloud"],
	},
	{
		id: "pi-dynamic-workflows",
		kind: "repositories",
		name: "Dynamic Workflows",
		packageName: "QuintinShaw/pi-dynamic-workflows",
		version: "3.4.0",
		source: "git:github.com/QuintinShaw/pi-dynamic-workflows@2c917ef28254611a8f70d990fc9e8706e33386a8",
		publisher: "QuintinShaw/pi-dynamic-workflows",
		description:
			"Model-routed subagents, resumable workflows, worktree isolation, cost accounting, and deep research.",
		tags: ["280+ stars", "MIT", "Subagents"],
	},
	{
		id: "pi-sandbox",
		kind: "repositories",
		name: "Pi Sandbox",
		packageName: "carderne/pi-sandbox",
		version: "0.5.1",
		source: "git:github.com/carderne/pi-sandbox@3323223af5f893a36fef5bd47d7f2377552fdd98",
		publisher: "carderne/pi-sandbox",
		description: "OS-level command sandboxing with interactive network and file-system permission prompts.",
		tags: ["160+ stars", "MIT", "Security"],
	},
	{
		id: "pi-tasks",
		kind: "repositories",
		name: "Pi Tasks",
		packageName: "tintinweb/pi-tasks",
		version: "0.7.1",
		source: "git:github.com/tintinweb/pi-tasks@d478be2f07d56c7af126876eb0a53a36f27bbf0a",
		publisher: "tintinweb/pi-tasks",
		description:
			"Persistent task tracking with dependency graphs, progress widgets, and optional subagent execution.",
		tags: ["140+ stars", "MIT", "Tasks"],
	},
	{
		id: "pi-permission-system",
		kind: "repositories",
		name: "Permission System",
		packageName: "MasuRii/pi-permission-system",
		version: "0.8.0",
		source: "git:github.com/MasuRii/pi-permission-system@9affcc9d1b52cd79b8bb7da2bebb761ac7e5b1d8",
		publisher: "MasuRii/pi-permission-system",
		description: "Layered access-control policies and approval enforcement for tools, skills, paths, and agents.",
		tags: ["110+ stars", "MIT", "Permissions"],
	},
	{
		id: "pi-agent-teams",
		kind: "repositories",
		name: "Agent Teams",
		packageName: "tmustier/pi-agent-teams",
		version: "0.5.6",
		source: "git:github.com/tmustier/pi-agent-teams@2c1776d2a68104aaadc1c622d8a704684c7c35d6",
		publisher: "tmustier/pi-agent-teams",
		description: "Team-based agent coordination with shared tasks, messaging, dependencies, and isolated workspaces.",
		tags: ["90+ stars", "MIT", "Multi-agent"],
	},
	{
		id: "pi-supervisor",
		kind: "repositories",
		name: "Pi Supervisor",
		packageName: "tintinweb/pi-supervisor",
		version: "0.5.0",
		source: "git:github.com/tintinweb/pi-supervisor@63dff13346afa39fe4e6f22001d2a5b7ee60ba8a",
		publisher: "tintinweb/pi-supervisor",
		description:
			"Goal-oriented supervision that keeps long coding sessions aligned with explicit completion criteria.",
		tags: ["60+ stars", "MIT", "Goals"],
	},
	{
		id: "pi-until-done",
		kind: "repositories",
		name: "Until Done",
		packageName: "srinitude/pi-until-done",
		version: "0.2.2",
		source: "git:github.com/srinitude/pi-until-done@02b0f3ba900cc01af6b70d2c95778bbf26bea5fc",
		publisher: "srinitude/pi-until-done",
		description:
			"Runs a request until objective completion criteria are satisfied or a verifiable blocker is reached.",
		tags: ["30+ stars", "MIT", "Persistence"],
	},
	{
		id: "pi-atlas",
		kind: "repositories",
		name: "Pi Atlas",
		packageName: "MohnDoe/pi-atlas",
		version: "0.2.1",
		source: "git:github.com/MohnDoe/pi-atlas@46f15dfe3fd58214839dac2aa0468a7c4b0fd99d",
		publisher: "MohnDoe/pi-atlas",
		description: "An interactive dashboard for inspecting Pi model usage, token consumption, and cost over time.",
		tags: ["30+ stars", "MIT", "Analytics"],
	},
];
