// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const AZURE_OPENAI_RESPONSES_MODELS = {
	"gpt-5-chat-latest": {
		id: "gpt-5-chat-latest",
		name: "GPT-5 Chat Latest",
		api: "azure-openai-responses",
		provider: "azure-openai-responses",
		baseUrl: "",
		reasoning: false,
		thinkingLevelMap: {"off":null},
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 10,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
	} satisfies Model<"azure-openai-responses">,
	"gpt-5.6-luna": {
		id: "gpt-5.6-luna",
		name: "GPT-5.6 Luna",
		api: "azure-openai-responses",
		provider: "azure-openai-responses",
		baseUrl: "",
		reasoning: true,
		thinkingLevelMap: {"off":null,"xhigh":"xhigh","max":"max"},
		input: ["text", "image"],
		cost: {
			input: 1,
			output: 6,
			cacheRead: 0.1,
			cacheWrite: 1.25,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	} satisfies Model<"azure-openai-responses">,
	"gpt-5.6-sol": {
		id: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		api: "azure-openai-responses",
		provider: "azure-openai-responses",
		baseUrl: "",
		reasoning: true,
		thinkingLevelMap: {"off":null,"xhigh":"xhigh","max":"max"},
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 30,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	} satisfies Model<"azure-openai-responses">,
	"gpt-5.6-terra": {
		id: "gpt-5.6-terra",
		name: "GPT-5.6 Terra",
		api: "azure-openai-responses",
		provider: "azure-openai-responses",
		baseUrl: "",
		reasoning: true,
		thinkingLevelMap: {"off":null,"xhigh":"xhigh","max":"max"},
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 15,
			cacheRead: 0.25,
			cacheWrite: 3.125,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	} satisfies Model<"azure-openai-responses">,
} as const;
